import Head from 'next/head'
import Image from 'next/image'
import { ReactElement } from 'react';
import { PageWithLayout } from '../components/Layouts/LayoutConfig';
import MainLayout from '../components/Layouts/MainLayout';
import Post from '../components/Post';
import styles from '../styles/HomePage.module.css'


const Home: PageWithLayout = () => {

    const changeFormHeight = () => {
        
        let textArea = (document.getElementById("newPostForm") as HTMLInputElement);
        let textAreaContainer = (document.getElementById("textAreaContainer") as HTMLElement)
        let newPostContainer = (document.getElementById("NewPostContainer") as HTMLElement)
        
        let numberOfRows = textArea?.value.split("\n").length;

        if(!textArea || !textAreaContainer || !newPostContainer){
            alert("New post container not found")
            return;
        }

        if(textArea?.value == ""){
            numberOfRows = 0;
        }

        if(numberOfRows >= 3){
            newPostContainer.style.height = "220px";
            textAreaContainer.style.height = "150px";
            textArea.style.height = "150px";
        }

        if(numberOfRows < 3){
            newPostContainer.style.height = "150px";
            textAreaContainer.style.height = "80px";
            textArea.style.height = "80px";
        }
    }


    return (
        <>
            <Head>
                <title>Kiwi | Home page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.NewPostContainer} id="NewPostContainer">
                <div className={styles.NewPostFormContainer} id="textAreaContainer">
                    <Image src='/images/user_icon.png' width="512" height="512" alt='User profile image'/>
                    <textarea id='newPostForm' onChange={changeFormHeight}/>
                </div>
                <div className={styles.NewPostToolbar}>
                    <p></p>
                    <button>Post</button>

                </div>

            </div>
            <div className='ContentContainer'>
                  
                <Post/>

                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                <Post/>
                    
                    
            </div>
        </>
    )
}

Home.getLayout = function getLayout(page: ReactElement){
    return(
        <MainLayout>
            {page}
        </MainLayout>
    )
}

export default Home